### ISSUE TITLE
Refatorar função getvalues

### ISSUE THREAD

**Issue by dunderbruno** [dunderbruno/B3#1]
módulo: preencher.py
função: getvalues

Na versão atual a mesma função executa os seguintes passos:
1. exibe quantas iterações foram executadas
2. consulta os dados de uma empresa (linhas 30-36)
3. salva os dados no banco de dados (linhas 37-42)

É necessário refatorar para que os passos 2 e 3 se tornem funções independentes.

**Comment by Vitormartins12** [comment]
trabalhando nisso!

**Comment by KeysonRaphael** [comment]
Trabalhando nisso

**Comment by Vitormartins12** [comment]
Encontrando o erro: sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 8, and there are 52 supplied. 

Parece que o formato da tabela que vc criou é diferente dos dados que pegamos da URL.

Consegue ajudar? @dunderbruno

**Comment by dunderbruno** [comment]
Vou verificar

**Comment by dunderbruno** [comment]
Acessei o site pelo browser pra olhar o html. A url ainda responde mas não gera mais os dados.
Mudou para https://economia.uol.com.br/cotacoes/bolsas/acoes/bvsp-bovespa/
Isso muda completamente as consultas.
Se quiser separar refatorar a função assim mesmo fique a vontade, vai servir de esboço para uma atualização completa no futuro.
Obrigado pela atenção.

**Comment by Vitormartins12** [comment]
Sugestão no PR #8 .
